// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StudyPlanner.Data.Context;

namespace StudyPlanner.Data.Migrations
{
    [DbContext(typeof(StudyPlannerContext))]
    [Migration("20200909012933_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("StudyPlanner.Business.Models.Conhecimento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("NivelConhecimentoAtual")
                        .HasColumnType("int");

                    b.Property<int>("NivelConhecimentoDesejado")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("varchar(200)");

                    b.Property<string>("PlanoAcao")
                        .IsRequired()
                        .HasColumnType("varchar(1000)");

                    b.Property<int>("Prioridade")
                        .HasColumnType("int");

                    b.Property<int>("TipoConhecimento")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Conhecimentos");
                });
#pragma warning restore 612, 618
        }
    }
}
